version: '3'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    volumes:
      - .:/hexagonal
    command: /wait-for-postgres.sh db python run.py
    restart: always
    depends_on:
      - db
    environment:
      PGPASSWORD: '${POSTGRES_PASSWORD}'
      ENV: '${ENV}'
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
